# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: "Build"

on:
  push:
    branches: [ master ]
    # Run action only if we have anything changed in the following folders
    paths:
    - src/**

  pull_request:
    branches: [ master, develop ]
    # Run action only if we have anything changed in the following folders
    paths:
    - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11, 16 ]

    steps:
    - uses: actions/checkout@v2

    - name: "Set up JDK"
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'

    - name: "Grant execute permission for gradlew"
      run: |
       chmod +x gradlew
       chmod +x gradle/wrapper/gradle-wrapper.jar

    - name: "Build with Gradle"
      run: ./gradlew build -x checkstyleMain -x checkstyleTest

